//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atensoli.Vista
{


	public partial class UCNavegacion
	{

		/// <summary>
		/// lnkRecepcionCorrespondencia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkRecepcionCorrespondencia;

		/// <summary>
		/// lnkCorrespondenciaPresidencia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaPresidencia;

		/// <summary>
		/// lnkCorrespondenciaAuditoria control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaAuditoria;

		/// <summary>
		/// lnkCorrespondenciaGestion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaGestion;

		/// <summary>
		/// lnkCorrespondenciaPlanificacion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaPlanificacion;

		/// <summary>
		/// lnkCorrespondenciaTecnologia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaTecnologia;

		/// <summary>
		/// lnkCorrespondenciaOAC control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaOAC;

		/// <summary>
		/// lnkCorrespondenciaAdministracion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaAdministracion;

		/// <summary>
		/// lnkCorrespondenciaRH control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaRH;

		/// <summary>
		/// lnkCorrespondenciaSeguridad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaSeguridad;

		/// <summary>
		/// lnkCorrespondenciaComercializacion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaComercializacion;

		/// <summary>
		/// lnkCorrespondenciaFinanciamiento control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaFinanciamiento;

		/// <summary>
		/// lnkCorrespondenciaTecnica control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaTecnica;

		/// <summary>
		/// lnkCorrespondenciaMovilidad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaMovilidad;

		/// <summary>
		/// lnkCorrespondenciaCobranzas control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaCobranzas;

		/// <summary>
		/// lnkCorrespondenciaConsultoria control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaConsultoria;

		/// <summary>
		/// lnkCorrespondenciaInternaPresidencia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaPresidencia;

		/// <summary>
		/// lnkCorrespondenciaInternaAuditoria control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaAuditoria;

		/// <summary>
		/// lnkCorrespondenciaInternaGestionComunicacional control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaGestionComunicacional;

		/// <summary>
		/// lnkCorrespondenciaInternaPlanificacion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaPlanificacion;

		/// <summary>
		/// lnkCorrespondenciaInternaTecnologia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaTecnologia;

		/// <summary>
		/// lnkCorrespondenciaInternaAtencion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaAtencion;

		/// <summary>
		/// lnkCorrespondenciaInternaAdministracion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaAdministracion;

		/// <summary>
		/// lnkCorrespondenciaInternaRH control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaRH;

		/// <summary>
		/// lnkCorrespondenciaInternaSeguridad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaSeguridad;

		/// <summary>
		/// lnkCorrespondenciaInternaComercializacion control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaComercializacion;

		/// <summary>
		/// lnkCorrespondenciaInternaFinanciamiento control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaFinanciamiento;

		/// <summary>
		/// lnkCorrespondenciaInternaTecnica control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaTecnica;

		/// <summary>
		/// lnkCorrespondenciaInternaMovilidad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaMovilidad;

		/// <summary>
		/// lnkCorrespondenciaInternaConsultoria control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaInternaConsultoria;

		/// <summary>
		/// lnkCorrespondenciaHistorialPorGerencia control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCorrespondenciaHistorialPorGerencia;

		/// <summary>
		/// lnkSeguridad control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkSeguridad;

		/// <summary>
		/// lnkCambiarClave control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkCambiarClave;
	}
}
